apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels: 
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: fedor89/user-image:v0
        imagePullPolicy: Always         
        ports:
          - containerPort: 8080
        env:
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-user
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-name
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-host
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: aws-profile
        - name: AWS_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: aws-bucket
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: jwt-secret
        volumeMounts:
        - name: aws-secret
          mountPath: "root/.aws/"
          readOnly: true
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
        